[package]
name = "tracy-sys"
version = "0.1.2"
authors = ["Kenichi Ishibashi <ishibashi.kenichi@gmail.com>"]
edition = "2021"

[build-dependencies]
cc = "1.0"

[features]
# Set TRACY_TIMER_QPC to allow non-precise timestamps.
allow-vm = []
