[package]
name = "rustracy"
version = "0.1.2"
authors = ["Kenichi Ishibashi <ishibashi.kenichi@gmail.com>"]
edition = "2021"

[dependencies]
tracy-sys = { path = "../tracy-sys" }
tracy-macros = { path = "../tracy-macros" }

[features]
allow-vm = [ "tracy-sys/allow-vm" ]
