[package]
name = "rustracy"
version = "0.1.1"
authors = ["Kenichi Ishibashi <ishibashi.kenichi@gmail.com>"]
edition = "2018"

[dependencies]
tracy-sys = { path = "../tracy-sys" }
tracy-macros = { path = "../tracy-macros" }

[features]
allow-vm = [ "tracy-sys/allow-vm" ]
